### ISSUE TITLE
filterDeep not working on deeply nested object

### ISSUE THREAD

**Issue by dnnsjsk** [YuriGor/deepdash#125]
Hey,

I've created a repro here:
https://codepen.io/dennisj/pen/dyZgJqg?editors=0010

The fourth object "themes/blockstudio-child/blockstudio" is not being filtered. I've added all nested paths to "childrenPaths". Am I missing something here?

**Comment by YuriGor** [comment]
Hi, not sure about your exact requirements, but adding option leavesOnly:false atleast makes your code return something.

**Comment by dnnsjsk** [comment]
That solved it, thanks!
