### ISSUE TITLE
Working with promises

### ISSUE THREAD

**Issue by emahuni** [YuriGor/deepdash#129]
I am trying to use some of these functions with promises and it doesn't work.

Any plans to support promises?

eg; 

```js
obj = await _.eachDeep(filters, async (val, key, parent, ctx) => {
   // ...
  parent[key] = await someAsyncFn(val);
}, { leavesOnly: true, checkCircular: true })
```

The `await` before _.eachDeep is trying to wait for all the promises. Problem is that each used value will end up being a `promise`, which goes back to the original problem of finding and awaiting each promise.

Is there a way to achieve this?

**Comment by emahuni** [comment]
So what I have done is this:

```js
const vows = [];
_.eachDeep(filters, (val, key, parent, ctx) => {
   // ...
  vows.push(someAsyncFn(val).then(res=>parent[key] = res);
}, { leavesOnly: true, checkCircular: true });
await Promise.all(vows)
```

I wish this could be done internally. You see the ...deep functions just have to detect if the callback is an async function, and do exactly like above before returning the modified obj. They do the `then` and setting of the `parent[key]`.

Detection of async function and vow keeping can be achieved like so:
```js
 if (cb instanceof Object.getPrototypeOf(async function () {}).constructor) {
    vows.push(cb(value, key, parent, ctx).then(res => parent[key] = res));
  } else {
    parent[key] = cb(value, key, parent, ctx); // normal callback function
  }
// ... then finally, before we return everything we return a promise that awaits the vows, but resolves to the object
return Promise.all(vows).then(res=>originalObjWeWereIterating)
```

That will allow the functions to be used like so:
```js
filters = await _.eachDeep(filters, async (val, key, parent, ctx) => {
   // ...
  return parent[key] = await someAsyncFn(val);
}, { leavesOnly: true, checkCircular: true });
```

it won't change semantics, but enhance the lib to work with promises.

**Comment by YuriGor** [comment]
Hi @emahuni - your implementation is 100% valid and if I would need to do it I would do the same.

Still it makes no sense to support it in deepdash internally: rare use case, but performance will be affected in all cases.
