### ISSUE TITLE
Typescript types defenition

### ISSUE THREAD

**Issue by YuriGor** [YuriGor/deepdash#14]
People ask for it.
Consider [Lodash types](https://www.npmjs.com/package/@types/lodash) as a starting point

**Comment by YuriGor** [comment]
I have no resources to invest in learning TypeScript but without it, I'll not be able to do this task well.
If anybody wants to do it - I'll be happy to help.

**Comment by YuriGor** [comment]
If anybody - let me know. Closed for now, maybe later I'll find some time for this.

**Comment by YuriGor** [comment]
Looks like I am going to get back to this.

**Comment by YuriGor** [comment]
Brief progress report, just to let people know it's not abandoned:

I decided to create type definitions files right in the sources of package.
For testing my type definitions I rely on builtin VS Code autocompletion/hint feature, which works with *d.ts files out of the box. Later I'll add some typescript linter.

And finally, I hope some ts dev will give some feedback does it works as expected because I will not be able to write typescript tests for it.

I am still trying to avoid learning typescript, but only definitions.
(I have nothing against TS, looks very interesting, but I have absolutely no time for it)

**Comment by xumx** [comment]
Thanks for the effort. I'm trying to use mapDeep in Typescript.

**Comment by YuriGor** [comment]
Hi, in few days I am gonna publish first full version of definitions, it already works for vscode autocompletion, but only if I pollute root directory.

How do you use it?
deepdash or deepdash-es package?
Mixin everything into lodash, add only selected methods, use standalone version?

When I try to move definitions to separate directory and set "types" property of package.json - only this particular entry point works, but not all this cherry-picked separate methods.

As I got from internets, only more or less nice way to not pollute root directory is to copy this definitions only on npm install phase.

**Comment by YuriGor** [comment]
Ok, v4.5.5 now has type definitions.

All the entry points covered in deepdash-es package,
but only with main 'deepdash' function definitions work in cjs "deepdash"  package
(not with cherry-picked methods, standalone version etc).

This is because "types" property of package.json can be set with a single value only and ts does no assumptions about other modules, even if ...d.ts files mirror all the file names.

I implemented these definitions relying on VS Code only. 
I am still not a TS guy, so please anybody give some feedback if it works or something broken.

**Comment by YuriGor** [comment]
If something - let me know here in comments, closing for now.

**Comment by gwsbhqt** [comment]
Many thanks for your efforts

**Comment by jwhitmarsh** [comment]
@YuriGor firstly thank you for this excellent library! Secondly, thank you for doing the TS defs! 

I've just come accross an issue using `filterDeep` where the options expects `cloneDeep` to be set. Looking at the docs this looks like it defaults to use `lodash.cloneDeep` so it's not a required property. If that's true, I think the type def should be

```ts
options?: {
    pathFormat?: "string" | "array"; // = "string";
    checkCircular?: boolean; // = false;
    keepCircular?: boolean; // = false;
    childrenPath?: Path[];
    includeRoot?: boolean;
    leavesOnly?: boolean; // = false;
    rootIsChildren?: boolean;
    callbackAfterIterate?: boolean; // = false;
    replaceCircularBy?: any;
    condense?: boolean;
    cloneDeep?: (value: any) => any; // <-- CHANGE HERE TO BE OPTIONAL
    onTrue?: {
      skipChildren?: boolean;
      cloneDeep?: boolean;
      keepIfEmpty?: boolean;
    };
    onFalse?: {
      skipChildren?: boolean;
      cloneDeep?: boolean;
      keepIfEmpty?: boolean;
    };
    onUndefined?: {
      skipChildren?: boolean;
      cloneDeep?: boolean;
      keepIfEmpty?: boolean;
    };
  }
```

**Comment by YuriGor** [comment]
HI @jwhitmarsh, thank you!
Yes, you are right, all the options always should be optional.
I see the same issue in the definitions of other methods where such an option exists, 
so probably it was just copypasted by me everywhere.

I am not sure when I'll fix it, no time currently,
so if you have some free time - PR is welcome.

To do it just fork/clone repo, fix ts files in `src` folder and do npm test - it will rebuild everything (=copy tx files to es folder in this case)

**Comment by YuriGor** [comment]
Ok, I found a minute for this, please check fixed v5.0.2

**Comment by arash-bizcover** [comment]
@YuriGor was this done already? I couldn't make it to show up in vscode autocomplete like regular lodash functions.

**Comment by YuriGor** [comment]
Hi, @arash-bizcover it was working at that moment, maybe something was changed in vscode or was broken later.
I don't use vscode and typescript and have no time to check even bug listed in issues,
so if you have some time/energy to spend on this - contributions are welcome.
