### ISSUE TITLE
Not able to break loop

### ISSUE THREAD

**Issue by rohandey** [YuriGor/deepdash#20]
Trying to break out of loop if key==2 is matched, but it does not work. What would be the right way to break out of loop

```javascript
_.eachDeep({ id: 1, children: [ {id: 2, children: [ { id: 3, children: []}]}]},(k, v, parent, context) => {
      if(k == 2) {
        return false;
      }
      console.log(k)

    });
```

**Comment by YuriGor** [comment]
Hi, @rohandey!
There is no builtin way to stop the iteration.
When you return false - only children of the current value will be skipped.
To stop iteration as fast as possible you will need to continuously return false from the rest of callbacks.
```js
    let breakLoop = false;
    _.eachDeep({ id: 1, children: [ {id: 2, children: [ { id: 3, children: []}]}]},
      (v,k, parent, context) => {
      if(breakLoop || v == 2) {
        breakLoop = true;
        return false;
      }
      console.log(k);
    }); 
```
Here is a [live example](https://codepen.io/yurigor/pen/NVrjRx?editors=0010) for your case.

**Comment by YuriGor** [comment]
Also notice, iteratee has value as a first argument, the key is second.
And in your example, there is no key which equals '2'. 
I see the only value which equals '2', but it has key equals 'id'

**Comment by rohandey** [comment]
Ok .. thanks for the reply and for this great library which is extremely useful in my current project.

**Comment by YuriGor** [comment]
Thank you, you're welcome!
Consider to :star: the project :wink:

**Comment by YuriGor** [comment]
Finally, I think about built in way to break the iteration. Something like 'break' method inside the context argument of iteratee

**Comment by YuriGor** [comment]
done in v4.3.0
