### ISSUE TITLE
deep map keys?

### ISSUE THREAD

**Issue by masciugo** [YuriGor/deepdash#26]
How can I deeply transform keys with deepdash?

**Comment by YuriGor** [comment]
Hi, currently there is no such method, I'll think about adding it in future release, when I'll have a bit of free time.
If you need it right now you can use [reduceDeep](https://deepdash.io/#reducedeep) instead

**Comment by masciugo** [comment]
For the sake of completeness, a specific method would be the best solution. But this is my implementation, which is quite satisfying 

```
mapDeep( obj, (value, key, parentValue, context) => {
  if (_.isPlainObject(value)) {
    return _.mapKeys(value, (v,k) => {
      switch (k) {
        case 'id':
          return 'value'
        case 'name':
          return 'label'
        default:
          return k
      }
    })
  } else {
    return value
  }
})
```

**Comment by YuriGor** [comment]
Looks like I've chosen the wrong name for `mapDeep`.
It actually should be mapValuesDeep, same as in lodash for one preserving object structure to be pair for `mapKeysDeep` requested above.
And `mapDeep` is the correct name for 'collectDeep' planned in #42

**Comment by YuriGor** [comment]
done in v5,0,0
*(that was tricky :sweat_smile:)*
[mapKeysDeep](https://deepdash.io/#mapkeysdeep)
also "old" mapDeep was renamed to [mapValuesDeep](https://deepdash.io/#mapvaluesdeep)
and [implemented](https://deepdash.io/#mapdeep) again to return just array
