### ISSUE TITLE
pickDeep mutates argument

### ISSUE THREAD

**Issue by masciugo** [YuriGor/deepdash#27]
In the following example I pass an array of paths to pickDeep and after execution it becomes an array of array! have a look to the console

https://codepen.io/masciugo/pen/MNjgra?editors=1111

**Comment by YuriGor** [comment]
Looks like as bug, thank you!
I convert paths from string to array format internally, so possibly I override argument instead of working with a copy.

**Comment by YuriGor** [comment]
fixed in v4.2.11
