### ISSUE TITLE
How about omitDeep?

### ISSUE THREAD

**Issue by JoeSchr** [YuriGor/deepdash#3]
E.g. omiting field named "__typename" from an nested object?

**Comment by YuriGor** [comment]
You can do this with [filterDeep](https://github.com/YuriGor/deepdash#filterdeep)

```js
    var obj = {
      a: { b: { c: [{ x: 1, y: 2, z: 3, __typename: 'nobodyCares' }] } },
    };
    var clean = _.filterDeep(obj, function(value, key) {
      return key != '__typename';
    });
```
[full test](https://github.com/YuriGor/deepdash/blob/f4a0f384bd7f3737eda5666f6cbc9615ad458551/test/issues.test.js#L67)

Do you think `omitDeep` shorthand will be handy?

**Comment by YuriGor** [comment]
I found it's not so simple as I suggested above with filterDeep. There are some nuances, need to care about.
Regex as a key argument is also supported.
Here is a [docs](https://github.com/YuriGor/deepdash#omitdeep)

Testing and feedback are welcome.

**Comment by JoeSchr** [comment]
Thanks I will use it and test it and if something comes up I will let you
know

**Comment by YuriGor** [comment]
Ok, you're welcome.

**Comment by JoeSchr** [comment]
I have a stupid question, how to I best use deepdash with `Vue.js` or to be more specific with ES6 `import`?

This is how I use lodash currently
```
import _ from "lodash";
```

This is from deepdash readme
```
//mixin new methods into Lodash object
const _ = require('deepdash')(require('lodash'));
```
Sorry, I'm still very inexperienced with the many different ways to import libraries with JS

**Comment by YuriGor** [comment]
Take a look [here](https://stackoverflow.com/questions/53679016/nodejs-requirerequire-to-import/53679055?r=SearchResults#53679055)
I need to add this to the readme finally.

**Comment by YuriGor** [comment]
For my taste 'require' sounds better than 'import')
Importing is weak and passive like you miss something and have to ask from outside.
Requiring is active and strong: you want it and you get it, no discussions.

**Comment by YuriGor** [comment]
README [updated](https://github.com/YuriGor/deepdash#installation)
