### ISSUE TITLE
 Type expected

### ISSUE THREAD

**Issue by barrct** [YuriGor/deepdash#64]
[default] <project path>\node_modules\deepdash-es\filterDeep.d.ts:12:5
    Type expected.
[default] Checking finished with 1 errors

This seems to be related to the extra pipe before void
  ) =>
    | void
    | boolean
    | {
        skipChildren: boolean;
        cloneDeep: boolean;
        keepIfEmpty: boolean;
      },

There are no errors when changed to
  ) =>
    void
    | boolean
    | {
        skipChildren: boolean;
        cloneDeep: boolean;
        keepIfEmpty: boolean;
      },

**Comment by YuriGor** [comment]
Hi, thank you, will fix. 
And how did you find this? tslint? Did you lint your own code or deepdash directly?

**Comment by YuriGor** [comment]
fixed in v5.2.0

**Comment by barrct** [comment]
I'm sorry, we run a system based on a template from wrapbootstrap and were just testing on the server:dev and the error showed up.Seemed like a simple accidental copy/paste bug.
Thank you for the quick update, 
    On Thursday, June 25, 2020, 02:05:07 AM EDT, Yuri Gor <notifications@github.com> wrote:  
 
 


Hi, thank you, will fix.
And how did you find this? tslint? Did you lint your own code or deepdash directly?
