### ISSUE TITLE
Transpile for ES5 / IE11 (object literal property value shorthand notation)

### ISSUE THREAD

**Issue by jnachtigall** [YuriGor/deepdash#67]
Similar to https://github.com/YuriGor/deepdash/issues/28 

In the code I only use `findValueDeep` via `import findValueDeep from "deepdash-es/findValueDeep";`

In IE 11 this results in:

> Error SCRIPT1003: ':' expected

![image](https://user-images.githubusercontent.com/3307404/89168449-311f8900-d57d-11ea-854f-5387197541b0.png)

Looking at the generated file, it seems like object literal property value shorthand notation is not being transpiled. Maybe a rule is missing for this.

**Current Workaround:**

In `webpack.config.js` add deepdash, so it is also transpiled by my App:
```js
          include: [
            path.resolve("./node_modules/deepdash-es"),
          ],
```

**Comment by YuriGor** [comment]
Sorry for the late response and thank you for report.
I think I will finally switch to babel

**Comment by YuriGor** [comment]
I just noticed you are using 'deepdash-es'
-es version of the package is not transpiled intentionally to let the bundler of your choice do the job.
Only cjs 'deepdash' package is transpiled (including /browser versions)
