### ISSUE TITLE
yarn cannot find the type definition after installing deepdash

### ISSUE THREAD

**Issue by rxliuli** [YuriGor/deepdash#74]
The es directory was excluded when npm was released. This should be an error

![image](https://user-images.githubusercontent.com/24560368/96845757-a23b5200-1483-11eb-86cb-f686b4f3725f.png)

**Comment by YuriGor** [comment]
Thank you for your feedback and PR!
Just published v5.3.1 let me know if something stilll wrong

**Comment by YuriGor** [comment]
Hi @rxliuli !
I know a long time passed, but if you are still using deepdash with typescript - could you please test v5.3.7?
Ideally you will not need separate deepdash-es package - just "deepdash" should work as es module.
And I also hope type definitions should also work and maybe even better:
![image](https://user-images.githubusercontent.com/6861317/115161638-2bcc8500-a09f-11eb-8a1a-9958be629a35.png)
