### ISSUE TITLE
"export 'default' (imported as 'deepdash') was not found in 'deepdash'

### ISSUE THREAD

**Issue by GaborTorma** [YuriGor/deepdash#77]
After installing 5.3.2 a received this error message in client side:

`"export 'default' (imported as 'deepdash') was not found in 'deepdash'`

To downgrading to 5.3.0 is everything works.

**Comment by YuriGor** [comment]
Hi, thanks for the report!
How to reproduce? I mean what is your setaup, is it deepdash or deepdash-es? Do you use webpack or whatever bundler?

**Comment by GaborTorma** [comment]
```
import lodash from 'lodash'
import deepdash from 'deepdash'

const _ = deepdash(lodash)

```

**Comment by YuriGor** [comment]
Ok, thank you, now I see.
https://codesandbox.io/s/deepdash-issue77-lfjfy

**Comment by YuriGor** [comment]
Hi @GaborTorma ! Sorry for long fix) 
Could you please test v5.3.7?
'deepdash' package should work now both as commonjs and as es module..
'deepdash-es' should also work but for imports only.

**Comment by YuriGor** [comment]
Ok, since I reproduced problem and now it's gone - closing this issue, lmk if something still wrong.
