### ISSUE TITLE
findDeep return types problem

### ISSUE THREAD

**Issue by casamia918** [YuriGor/deepdash#84]
```typescript
export interface IDeepEntry {
  value: any;
  key?: string | number;
  path?: Path;
  parent?: IDeepEntry;
  /**
   * contains matched childrenPath path of this parent node, chosen from childrenPath array, if it was specified.
   */
  childrenPath?: Path;
}

```

For now, IDeepEntry interface is defined as above.
But it has no context field. Which should be `IIterateeContext`
Also, the type of parent field is defined as IDeepEntry. But when I call findDeep, type of returnedObj.parent is not IDeepEntry (it is parent.value obj)

**Comment by casamia918** [comment]
https://github.com/YuriGor/deepdash/pull/85

**Comment by YuriGor** [comment]
Actually there is a real issue with types here, findDeep return type should not be IDeepEntry, but a separate type.

**Comment by YuriGor** [comment]
I have no time and very low motivation about this issue, because I am not using TS.
For the same reason it's difficult for me to develop TS-related stuff.
So if someone from TS world have free time to take a look at this issue - PR is very welcome.
