### ISSUE TITLE
findDeep is not a function

### ISSUE THREAD

**Issue by corysimmons** [YuriGor/deepdash#88]
I keep trying to use this pkg on https://npm.runkit.com/deepdash (and locally) but methods don't seem to work as the docs say:

![image](https://user-images.githubusercontent.com/224636/107047775-32cd4200-6796-11eb-8d67-0b4569f388c5.png)

**Comment by YuriGor** [comment]
Hi, please check [docs](https://deepdash.io/#installation)
If you want to use deepdash as standalone lib - require 'deepdash/standalone'
Here is an example:
https://runkit.com/embed/75gb9jgrz92t
