### ISSUE TITLE
mapValuesDeep mutates the original object if `leavesOnly: false`

### ISSUE THREAD

**Issue by lewisblackwood** [YuriGor/deepdash#99]
Hi,

Great library 👍 

I found using `mapValuesDeep` that if the options are left at the default `leavesOnly: false`, then it mutates the original object. If `leavesOnly: true` then the original object is not mutated.

You can see an example repl.it [here](https://replit.com/@lewisblackwood/mapValuesDeep).

```javascript
// leavesOnly: true
{ sourceData: { hello: 'world' }, mappedData: { hello: 'WORLD' } }
// leavesOnly: false
{ sourceData: { hello: 'WORLD' }, mappedData: { hello: 'WORLD' } }
```

Is this the expected behaviour?

**Comment by YuriGor** [comment]
Hi, thank you for report, looks like a bug, will check in next few days.
